name: publish

on:
  push:
      branches:
        - master

jobs:
  build:
    name: Docker Image
    runs-on: ubuntu-latest
    env:
      GITHUB_PACKAGE: ghcr.io/vouch-opensource/amazon-ssm-agent
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=1 docker build . \
          --progress=plain \
          --tag ${{ env.GITHUB_PACKAGE }}:${{ github.sha }}
      - name: Docker Login Github
        run: docker login -u publisher -p ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - name: Publish Docker image Github
        run: docker push $GITHUB_PACKAGE:${{ github.sha }}
